<a href="https://colab.research.google.com/github/hafizur45/Job-Success-prediction-bangladesh/blob/main/Research2_jobsuccess_prediction_Copy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive

# Mount Google Drive
drive.mount('/content/drive')


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
df=pd.read_excel('/content/drive/MyDrive/Datasets/Copy of data.xlsx')

In [ ]:
df.head()

ID                  Name  Gender  Age  Bachelor  \
0   26000     Md. Taslim Mahmud       1   44         1   
1  135207    Ashfaq Newaz Ahmed       1   41         1   
2  208486     S.M. Shafiul Azam       1   52         1   
3  209871  Kazi Mohammadun Nabi       1   47         1   
4  237524           Aslam Uddin       1   45         1   

   Bachelor Education Organization (Public / Private)  B_SUBJECT  Masters  \
0                                                  1           0        1   
1                                                  1           0        1   
2                                                  1           0        1   
3                                                  1           1        0   
4                                                  1           0        1   

   Masters Education Organization (Public / Private)  m_SUBJECT  video cv  \
0                                                  1          0         1   
1                                                  1          0         1   
2                                                  1          0         1   
3                                                  0          0         1   
4                                                  1          0         1   

   Technical Skill  SOFT Skill  EDU_Result  EXPerienced  output  
0                1           0           1            1       1  
1                1           1           1            1       1  
2                0           0           1            0       0  
3                0           1           1            1       1  
4                0           0           1            0       0

In [ ]:
df = df.drop(['ID', 'Name'], axis=1)


In [ ]:
# Assuming df is your original DataFrame
df = df.dropna()  # Drops rows containing any NaN values

# Now, you can proceed to split the data and train the model
x = df.iloc[:, :-1]
y = df.iloc[:, -1]




In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
import numpy as np

# Assuming you have 'x' and 'y' from the previous code

# Split the data into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

# Initialize the linear regression model
model = LinearRegression()

# Train the model on the training set
model.fit(x_train, y_train)

# Make predictions on the test set
y_pred = model.predict(x_test)

# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)

print(f"Mean Squared Error: {mse}")
print(f"Root Mean Squared Error: {rmse}")

# Optionally, you can also print the coefficients and intercept
print("Coefficients:", model.coef_)
print("Intercept:", model.intercept_)


Mean Squared Error: 0.07551300177552273
Root Mean Squared Error: 0.2747962914151549
Coefficients: [ 0.00121251 -0.00169859 -0.02129704 -0.02129704  0.03920786  0.01263861
  0.01263861 -0.01130895  0.25229652  0.41045685  0.34677724  0.04932276
  0.28311694]
Intercept: -0.12834132705215406


In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Assuming 'df' is your DataFrame
X = df.drop('output', axis=1)
y = df['output']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize the logistic regression model
model = LogisticRegression()

# Train the model on the training set
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print(f"Accuracy: {accuracy}")
print(f"Confusion Matrix:\n{conf_matrix}")
print(f"Classification Report:\n{classification_rep}")


Accuracy: 0.9493525179856115
Confusion Matrix:
[[10895   766]
 [  114  5600]]
Classification Report:
              precision    recall  f1-score   support

           0       0.99      0.93      0.96     11661
           1       0.88      0.98      0.93      5714

    accuracy                           0.95     17375
   macro avg       0.93      0.96      0.94     17375
weighted avg       0.95      0.95      0.95     17375



/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [ ]:
from sklearn.svm import SVC

# Initialize the SVM model
svm_model = SVC()

# Train the SVM model on the training set
svm_model.fit(X_train, y_train)

# Make predictions on the test set
svm_y_pred = svm_model.predict(X_test)

# Evaluate the SVM model
svm_accuracy = accuracy_score(y_test, svm_y_pred)
svm_conf_matrix = confusion_matrix(y_test, svm_y_pred)
svm_classification_rep = classification_report(y_test, svm_y_pred)

print("SVM Model:")
print(f"Accuracy: {svm_accuracy}")
print(f"Confusion Matrix:\n{svm_conf_matrix}")
print(f"Classification Report:\n{svm_classification_rep}")


SVM Model:
Accuracy: 0.9388776978417266
Confusion Matrix:
[[10599  1062]
 [    0  5714]]
Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.91      0.95     11661
           1       0.84      1.00      0.91      5714

    accuracy                           0.94     17375
   macro avg       0.92      0.95      0.93     17375
weighted avg       0.95      0.94      0.94     17375



In [ ]:
from sklearn.tree import DecisionTreeClassifier

# Initialize the Decision Tree model
dt_model = DecisionTreeClassifier()

# Train the Decision Tree model on the training set
dt_model.fit(X_train, y_train)

# Make predictions on the test set
dt_y_pred = dt_model.predict(X_test)

# Evaluate the Decision Tree model
dt_accuracy = accuracy_score(y_test, dt_y_pred)
dt_conf_matrix = confusion_matrix(y_test, dt_y_pred)
dt_classification_rep = classification_report(y_test, dt_y_pred)

print("\nDecision Tree Model:")
print(f"Accuracy: {dt_accuracy}")
print(f"Confusion Matrix:\n{dt_conf_matrix}")
print(f"Classification Report:\n{dt_classification_rep}")



Decision Tree Model:
Accuracy: 0.9490071942446043
Confusion Matrix:
[[10882   779]
 [  107  5607]]
Classification Report:
              precision    recall  f1-score   support

           0       0.99      0.93      0.96     11661
           1       0.88      0.98      0.93      5714

    accuracy                           0.95     17375
   macro avg       0.93      0.96      0.94     17375
weighted avg       0.95      0.95      0.95     17375



In [ ]:
from sklearn.ensemble import RandomForestClassifier

# Initialize the Random Forest model
rf_model = RandomForestClassifier()

# Train the Random Forest model on the training set
rf_model.fit(X_train, y_train)

# Make predictions on the test set
rf_y_pred = rf_model.predict(X_test)

# Evaluate the Random Forest model
rf_accuracy = accuracy_score(y_test, rf_y_pred)
rf_conf_matrix = confusion_matrix(y_test, rf_y_pred)
rf_classification_rep = classification_report(y_test, rf_y_pred)

print("\nRandom Forest Model:")
print(f"Accuracy: {rf_accuracy}")
print(f"Confusion Matrix:\n{rf_conf_matrix}")
print(f"Classification Report:\n{rf_classification_rep}")



Random Forest Model:
Accuracy: 0.9502733812949641
Confusion Matrix:
[[10878   783]
 [   81  5633]]
Classification Report:
              precision    recall  f1-score   support

           0       0.99      0.93      0.96     11661
           1       0.88      0.99      0.93      5714

    accuracy                           0.95     17375
   macro avg       0.94      0.96      0.95     17375
weighted avg       0.95      0.95      0.95     17375



In [ ]:
!pip3 install xgboost

from xgboost import XGBClassifier

# Initialize the XGBoost model
xgb_model = XGBClassifier()

# Train the XGBoost model on the training set
xgb_model.fit(X_train, y_train)

# Make predictions on the test set
xgb_y_pred = xgb_model.predict(X_test)

# Evaluate the XGBoost model
xgb_accuracy = accuracy_score(y_test, xgb_y_pred)
xgb_conf_matrix = confusion_matrix(y_test, xgb_y_pred)
xgb_classification_rep = classification_report(y_test, xgb_y_pred)

print("\nXGBoost Model:")
print(f"Accuracy: {xgb_accuracy}")
print(f"Confusion Matrix:\n{xgb_conf_matrix}")
print(f"Classification Report:\n{xgb_classification_rep}")



XGBoost Model:
Accuracy: 0.9518273381294964
Confusion Matrix:
[[10860   801]
 [   36  5678]]
Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.93      0.96     11661
           1       0.88      0.99      0.93      5714

    accuracy                           0.95     17375
   macro avg       0.94      0.96      0.95     17375
weighted avg       0.96      0.95      0.95     17375



In [ ]:
from sklearn.model_selection import GridSearchCV

# Example for Logistic Regression
param_grid = {
    'C': [0.001, 0.01, 0.1, 1, 10, 100],
    'penalty': ['l1', 'l2']
}

grid_search = GridSearchCV(LogisticRegression(), param_grid, cv=5)
grid_search.fit(X_train, y_train)

best_params = grid_search.best_params_
best_model = grid_search.best_estimator_

# Evaluate the best model
y_pred_best = best_model.predict(X_test)
accuracy_best = accuracy_score(y_test, y_pred_best)
print(f"Best Model Accuracy: {accuracy_best}")


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

Best Model Accuracy: 0.949294964028777


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [ ]:
from sklearn.model_selection import cross_val_score

# Example for Random Forest
rf_model = RandomForestClassifier()

# Use cross_val_score to evaluate the model with different hyperparameter settings
scores = cross_val_score(rf_model, X_train, y_train, cv=5)
average_accuracy = np.mean(scores)

print(f"Average Cross-Validation Accuracy: {average_accuracy}")


Average Cross-Validation Accuracy: 0.9509633124064099


In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression

# Define the hyperparameter grid
param_grid = {
    'penalty': ['l1', 'l2'],
    'C': [0.001, 0.01, 0.1, 1, 10, 100],
    'solver': ['liblinear', 'saga']
}

# Initialize the Logistic Regression model
model = LogisticRegression()

# Initialize GridSearchCV
grid_search = GridSearchCV(estimator=model, param_grid=param_grid, scoring='accuracy', cv=5)

# Fit the model with different hyperparameter combinations
grid_search.fit(X_train, y_train)

# Get the best parameters and the best model
best_params = grid_search.best_params_
best_model = grid_search.best_estimator_

# Evaluate the best model
y_pred_best = best_model.predict(X_test)
accuracy_best = accuracy_score(y_test, y_pred_best)
print(f"Best Model Accuracy: {accuracy_best}")


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which 

Best Model Accuracy: 0.9499280575539568


In [ ]:
from sklearn.model_selection import RandomizedSearchCV

# Define the hyperparameter distribution
param_dist = {
    'penalty': ['l1', 'l2'],
    'C': [0.001, 0.01, 0.1, 1, 10, 100],
    'solver': ['liblinear', 'saga']
}

# Initialize the Logistic Regression model
model = LogisticRegression()

# Initialize RandomizedSearchCV
random_search = RandomizedSearchCV(estimator=model, param_distributions=param_dist, scoring='accuracy', cv=5, n_iter=10)

# Fit the model with different hyperparameter combinations
random_search.fit(X_train, y_train)

# Get the best parameters and the best model
best_params = random_search.best_params_
best_model = random_search.best_estimator_

# Evaluate the best model
y_pred_best = best_model.predict(X_test)
accuracy_best = accuracy_score(y_test, y_pred_best)
print(f"Best Model Accuracy: {accuracy_best}")


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which 

Best Model Accuracy: 0.9492374100719424


In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.model_selection import GridSearchCV



# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize the Logistic Regression model
model = LogisticRegression()

# Train the model on the training set
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print(f"Accuracy: {accuracy}")
print(f"Confusion Matrix:\n{conf_matrix}")
print(f"Classification Report:\n{classification_rep}")

# Hyperparameter Tuning using Grid Search
param_grid = {
    'penalty': ['l1', 'l2'],
    'C': [0.001, 0.01, 0.1, 1, 10, 100],
    'solver': ['liblinear', 'saga']
}

grid_search = GridSearchCV(LogisticRegression(), param_grid, cv=5)
grid_search.fit(X_train, y_train)

best_params = grid_search.best_params_
best_model = grid_search.best_estimator_

# Evaluate the best model
y_pred_best = best_model.predict(X_test)
accuracy_best = accuracy_score(y_test, y_pred_best)
print(f"\nBest Model Accuracy after Hyperparameter Tuning: {accuracy_best}")


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Accuracy: 0.9493525179856115
Confusion Matrix:
[[10895   766]
 [  114  5600]]
Classification Report:
              precision    recall  f1-score   support

           0       0.99      0.93      0.96     11661
           1       0.88      0.98      0.93      5714

    accuracy                           0.95     17375
   macro avg       0.93      0.96      0.94     17375
weighted avg       0.95      0.95      0.95     17375



/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which 


Best Model Accuracy after Hyperparameter Tuning: 0.9492374100719424


In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV, RandomizedSearchCV
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report



# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Random Forest Hyperparameter Tuning
param_grid_rf = {
    'n_estimators': [50, 100, 150],
    'max_depth': [None, 10, 20, 30],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

grid_search_rf = GridSearchCV(RandomForestClassifier(), param_grid_rf, cv=5)
grid_search_rf.fit(X_train, y_train)

best_params_rf = grid_search_rf.best_params_
best_model_rf = grid_search_rf.best_estimator_

# Evaluate the best Random Forest model
y_pred_rf = best_model_rf.predict(X_test)
accuracy_rf = accuracy_score(y_test, y_pred_rf)
print(f"\nBest Random Forest Model Accuracy after Hyperparameter Tuning: {accuracy_rf}")

# XGBoost Hyperparameter Tuning
param_dist_xgb = {
    'max_depth': [3, 5, 7, 10],
    'learning_rate': [0.01, 0.1, 0.2, 0.3],
    'n_estimators': [50, 100, 150, 200],
    'subsample': [0.8, 0.9, 1.0],
    'colsample_bytree': [0.8, 0.9, 1.0],
    'gamma': [0, 1, 2],
    'reg_alpha': [0, 0.1, 0.5, 1]
}

random_search_xgb = RandomizedSearchCV(XGBClassifier(), param_distributions=param_dist_xgb, n_iter=10, cv=5)
random_search_xgb.fit(X_train, y_train)

best_params_xgb = random_search_xgb.best_params_
best_model_xgb = random_search_xgb.best_estimator_

# Evaluate the best XGBoost model
y_pred_xgb = best_model_xgb.predict(X_test)
accuracy_xgb = accuracy_score(y_test, y_pred_xgb)
print(f"\nBest XGBoost Model Accuracy after Hyperparameter Tuning: {accuracy_xgb}")



Best Random Forest Model Accuracy after Hyperparameter Tuning: 0.9518273381294964

Best XGBoost Model Accuracy after Hyperparameter Tuning: 0.9520575539568346


In [ ]:
# Confusion Matrix for Random Forest
conf_matrix_rf = confusion_matrix(y_test, y_pred_rf)
print("\nConfusion Matrix for Random Forest:")
print(conf_matrix_rf)

# Confusion Matrix for XGBoost
conf_matrix_xgb = confusion_matrix(y_test, y_pred_xgb)
print("\nConfusion Matrix for XGBoost:")
print(conf_matrix_xgb)



Confusion Matrix for Random Forest:
[[10861   800]
 [   37  5677]]

Confusion Matrix for XGBoost:
[[10853   808]
 [   25  5689]]


In [ ]:

# Print classification report for Random Forest
report_rf = classification_report(y_test, y_pred_rf)
print("\nClassification Report for Random Forest:")
print(report_rf)

# Print classification report for XGBoost
report_xgb = classification_report(y_test, y_pred_xgb)
print("\nClassification Report for XGBoost:")
print(report_xgb)


Classification Report for Random Forest:
              precision    recall  f1-score   support

           0       1.00      0.93      0.96     11661
           1       0.88      0.99      0.93      5714

    accuracy                           0.95     17375
   macro avg       0.94      0.96      0.95     17375
weighted avg       0.96      0.95      0.95     17375


Classification Report for XGBoost:
              precision    recall  f1-score   support

           0       1.00      0.93      0.96     11661
           1       0.88      1.00      0.93      5714

    accuracy                           0.95     17375
   macro avg       0.94      0.96      0.95     17375
weighted avg       0.96      0.95      0.95     17375



In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report



# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize the Random Forest model
model = RandomForestClassifier(n_estimators=100, random_state=42)

# Train the model on the training set
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print(f"Accuracy: {accuracy}")
print(f"Confusion Matrix:\n{conf_matrix}")
print(f"Classification Report:\n{classification_rep}")


Accuracy: 0.9502158273381295
Confusion Matrix:
[[10876   785]
 [   80  5634]]
Classification Report:
              precision    recall  f1-score   support

           0       0.99      0.93      0.96     11661
           1       0.88      0.99      0.93      5714

    accuracy                           0.95     17375
   macro avg       0.94      0.96      0.95     17375
weighted avg       0.95      0.95      0.95     17375



In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize models
logistic_regression_model = LogisticRegression(random_state=42)
decision_tree_model = DecisionTreeClassifier(random_state=42)
svm_model = SVC(random_state=42)
xgboost_model = XGBClassifier(random_state=42)

# Train models
logistic_regression_model.fit(X_train, y_train)
decision_tree_model.fit(X_train, y_train)
svm_model.fit(X_train, y_train)
xgboost_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred_lr = logistic_regression_model.predict(X_test)
y_pred_dt = decision_tree_model.predict(X_test)
y_pred_svm = svm_model.predict(X_test)
y_pred_xgb = xgboost_model.predict(X_test)

# Evaluate models
accuracy_lr = accuracy_score(y_test, y_pred_lr)
accuracy_dt = accuracy_score(y_test, y_pred_dt)
accuracy_svm = accuracy_score(y_test, y_pred_svm)
accuracy_xgb = accuracy_score(y_test, y_pred_xgb)

print("Logistic Regression Accuracy:", accuracy_lr)
print("Decision Tree Accuracy:", accuracy_dt)
print("SVM Accuracy:", accuracy_svm)
print("XGBoost Accuracy:", accuracy_xgb)


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Logistic Regression Accuracy: 0.9493525179856115
Decision Tree Accuracy: 0.9490071942446043
SVM Accuracy: 0.9388776978417266
XGBoost Accuracy: 0.9518273381294964


In [ ]:
from sklearn.neighbors import KNeighborsClassifier

knn_model = KNeighborsClassifier()
knn_model.fit(X_train, y_train)
y_pred_knn = knn_model.predict(X_test)
accuracy_knn = accuracy_score(y_test, y_pred_knn)
print("KNN Accuracy:", accuracy_knn)


KNN Accuracy: 0.9425611510791367


In [ ]:
from sklearn.naive_bayes import GaussianNB

nb_model = GaussianNB()
nb_model.fit(X_train, y_train)
y_pred_nb = nb_model.predict(X_test)
accuracy_nb = accuracy_score(y_test, y_pred_nb)
print("Naive Bayes Accuracy:", accuracy_nb)



Naive Bayes Accuracy: 0.6504172661870503


In [ ]:
from sklearn.svm import LinearSVC

linear_svm_model = LinearSVC()
linear_svm_model.fit(X_train, y_train)
y_pred_linear_svm = linear_svm_model.predict(X_test)
accuracy_linear_svm = accuracy_score(y_test, y_pred_linear_svm)
print("Linear SVM Accuracy:", accuracy_linear_svm)


Linear SVM Accuracy: 0.951021582733813


/usr/local/lib/python3.10/dist-packages/sklearn/svm/_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


In [ ]:
from sklearn.ensemble import AdaBoostClassifier

adaboost_model = AdaBoostClassifier(n_estimators=50, random_state=42)
adaboost_model.fit(X_train, y_train)
y_pred_adaboost = adaboost_model.predict(X_test)
accuracy_adaboost = accuracy_score(y_test, y_pred_adaboost)
print("AdaBoost Accuracy:", accuracy_adaboost)


AdaBoost Accuracy: 0.9225323741007194


In [ ]:
from sklearn.neural_network import MLPClassifier

mlp_model = MLPClassifier(hidden_layer_sizes=(100,), max_iter=1000, random_state=42)
mlp_model.fit(X_train, y_train)
y_pred_mlp = mlp_model.predict(X_test)
accuracy_mlp = accuracy_score(y_test, y_pred_mlp)
print("Multilayer Perceptron Accuracy:", accuracy_mlp)


Multilayer Perceptron Accuracy: 0.952


In [ ]:
df.shape

(86874, 14)

In [ ]:
df

Gender  Age  Bachelor  \
0           1   44         1   
1           1   41         1   
2           1   52         1   
3           1   47         1   
4           1   45         1   
...       ...  ...       ...   
86869       1   20         0   
86870       1   18         0   
86871       1   28         1   
86872       1   22         1   
86873       1   22         1   

       Bachelor Education Organization (Public / Private)  B_SUBJECT  Masters  \
0                                                      1           0        1   
1                                                      1           0        1   
2                                                      1           0        1   
3                                                      1           1        0   
4                                                      1           0        1   
...                                                  ...         ...      ...   
86869                                                  0           0        0   
86870                                                  0           0        0   
86871                                                  1           0        1   
86872                                                  1           0        0   
86873                                                  1           0        0   

       Masters Education Organization (Public / Private)  m_SUBJECT  video cv  \
0                                                      1          0         1   
1                                                      1          0         1   
2                                                      1          0         1   
3                                                      0          0         1   
4                                                      1          0         1   
...                                                  ...        ...       ...   
86869                                                  0          0         0   
86870                                                  0          0         1   
86871                                                  1          0         1   
86872                                                  0          0         1   
86873                                                  0          0         0   

       Technical Skill  SOFT Skill  EDU_Result  EXPerienced  output  
0                    1           0           1            1       1  
1                    1           1           1            1       1  
2                    0           0           1            0       0  
3                    0           1           1            1       1  
4                    0           0           1            0       0  
...                ...         ...         ...          ...     ...  
86869                0           0           0            0       0  
86870                0           0           0            0       0  
86871                1           0           1            1       0  
86872                0           1           0            1       0  
86873                0           0           0            0       0  

[86874 rows x 14 columns]

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Assuming df is your original DataFrame
df = df.dropna()  # Drops rows containing any NaN values

# Now, you can proceed to split the data and train the model
x = df.iloc[:, :-1]
y = df.iloc[:, -1]

# Split data into train and test sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

# Initialize models
models = {
    "Gradient Boosting": GradientBoostingClassifier(),
    "Random Forest": RandomForestClassifier(),
    "Decision Tree": DecisionTreeClassifier(),
    "Logistic Regression": LogisticRegression(),
    "SVM": SVC()
}

# Train and evaluate models
for name, model in models.items():
    model.fit(x_train, y_train)
    y_pred = model.predict(x_test)

    accuracy = accuracy_score(y_test, y_pred)
    print(f"Accuracy for {name}: {accuracy:.2f}")

    classification_rep = classification_report(y_test, y_pred)
    print(f"Classification Report for {name}:\n{classification_rep}")

    conf_matrix = confusion_matrix(y_test, y_pred)
    print(f"Confusion Matrix for {name}:\n{conf_matrix}\n")


Accuracy for Gradient Boosting: 0.95
Classification Report for Gradient Boosting:
              precision    recall  f1-score   support

           0       1.00      0.93      0.96     11661
           1       0.88      1.00      0.93      5714

    accuracy                           0.95     17375
   macro avg       0.94      0.96      0.95     17375
weighted avg       0.96      0.95      0.95     17375

Confusion Matrix for Gradient Boosting:
[[10852   809]
 [   23  5691]]

Accuracy for Random Forest: 0.95
Classification Report for Random Forest:
              precision    recall  f1-score   support

           0       0.99      0.93      0.96     11661
           1       0.88      0.99      0.93      5714

    accuracy                           0.95     17375
   macro avg       0.94      0.96      0.95     17375
weighted avg       0.96      0.95      0.95     17375

Confusion Matrix for Random Forest:
[[10877   784]
 [   76  5638]]

Accuracy for Decision Tree: 0.95
Classification Re

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Accuracy for Logistic Regression: 0.95
Classification Report for Logistic Regression:
              precision    recall  f1-score   support

           0       0.99      0.93      0.96     11661
           1       0.88      0.98      0.93      5714

    accuracy                           0.95     17375
   macro avg       0.93      0.96      0.94     17375
weighted avg       0.95      0.95      0.95     17375

Confusion Matrix for Logistic Regression:
[[10895   766]
 [  114  5600]]

Accuracy for SVM: 0.94
Classification Report for SVM:
              precision    recall  f1-score   support

           0       1.00      0.91      0.95     11661
           1       0.84      1.00      0.91      5714

    accuracy                           0.94     17375
   macro avg       0.92      0.95      0.93     17375
weighted avg       0.95      0.94      0.94     17375

Confusion Matrix for SVM:
[[10599  1062]
 [    0  5714]]



In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Assuming df is your original DataFrame
df = df.dropna()  # Drops rows containing any NaN values

# Now, you can proceed to split the data and train the model
x = df.iloc[:, :-1]
y = df.iloc[:, -1]

# Split data into train and test sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

# Initialize models
models = {
    "Gradient Boosting": GradientBoostingClassifier(),
    "Random Forest": RandomForestClassifier(),
    "Decision Tree": DecisionTreeClassifier(),
    "Logistic Regression": LogisticRegression(),
    "SVM": SVC()
}

# Train and evaluate models
for name, model in models.items():
    model.fit(x_train, y_train)
    y_pred = model.predict(x_test)

    accuracy = accuracy_score(y_test, y_pred)
    print(f"Accuracy for {name}: {accuracy:.2f}")

    classification_rep = classification_report(y_test, y_pred)
    print(f"Classification Report for {name}:\n{classification_rep}")

    conf_matrix = confusion_matrix(y_test, y_pred)
    print(f"Confusion Matrix for {name}:\n{conf_matrix}\n")


Accuracy for Gradient Boosting: 0.95
Classification Report for Gradient Boosting:
              precision    recall  f1-score   support

           0       1.00      0.93      0.96     11661
           1       0.88      1.00      0.93      5714

    accuracy                           0.95     17375
   macro avg       0.94      0.96      0.95     17375
weighted avg       0.96      0.95      0.95     17375

Confusion Matrix for Gradient Boosting:
[[10852   809]
 [   23  5691]]

Accuracy for Random Forest: 0.95
Classification Report for Random Forest:
              precision    recall  f1-score   support

           0       0.99      0.93      0.96     11661
           1       0.88      0.99      0.93      5714

    accuracy                           0.95     17375
   macro avg       0.94      0.96      0.95     17375
weighted avg       0.95      0.95      0.95     17375

Confusion Matrix for Random Forest:
[[10877   784]
 [   81  5633]]

Accuracy for Decision Tree: 0.95
Classification Re

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Accuracy for Logistic Regression: 0.95
Classification Report for Logistic Regression:
              precision    recall  f1-score   support

           0       0.99      0.93      0.96     11661
           1       0.88      0.98      0.93      5714

    accuracy                           0.95     17375
   macro avg       0.93      0.96      0.94     17375
weighted avg       0.95      0.95      0.95     17375

Confusion Matrix for Logistic Regression:
[[10895   766]
 [  114  5600]]

Accuracy for SVM: 0.94
Classification Report for SVM:
              precision    recall  f1-score   support

           0       1.00      0.91      0.95     11661
           1       0.84      1.00      0.91      5714

    accuracy                           0.94     17375
   macro avg       0.92      0.95      0.93     17375
weighted avg       0.95      0.94      0.94     17375

Confusion Matrix for SVM:
[[10599  1062]
 [    0  5714]]



In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix

# Assuming df is your original DataFrame
df = df.dropna()  # Drops rows containing any NaN values

# Now, you can proceed to split the data and train the model
x = df.iloc[:, :-1]
y = df.iloc[:, -1]

# Split data into train and test sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

# Initialize models
models = {
    "Gradient Boosting": GradientBoostingClassifier(),
    "Random Forest": RandomForestClassifier(),
    "Decision Tree": DecisionTreeClassifier(),
    "Logistic Regression": LogisticRegression(),
    "SVM": SVC()
}

# Train and evaluate models
for name, model in models.items():
    model.fit(x_train, y_train)
    y_pred = model.predict(x_test)

    accuracy = accuracy_score(y_test, y_pred)
    print(f"Accuracy for {name}: {accuracy:.2f}")

    conf_matrix = confusion_matrix(y_test, y_pred)
    print(f"Confusion Matrix for {name}:\n{conf_matrix}\n")



Accuracy for Gradient Boosting: 0.95
Confusion Matrix for Gradient Boosting:
[[10852   809]
 [   23  5691]]

Accuracy for Random Forest: 0.95
Confusion Matrix for Random Forest:
[[10878   783]
 [   81  5633]]

Accuracy for Decision Tree: 0.95
Confusion Matrix for Decision Tree:
[[10882   779]
 [  107  5607]]



/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Accuracy for Logistic Regression: 0.95
Confusion Matrix for Logistic Regression:
[[10895   766]
 [  114  5600]]

Accuracy for SVM: 0.94
Confusion Matrix for SVM:
[[10599  1062]
 [    0  5714]]



In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix

# Assuming df is your original DataFrame
df = df.dropna()  # Drops rows containing any NaN values

# Now, you can proceed to split the data and train the model
x = df.iloc[:, :-1]
y = df.iloc[:, -1]

# Split data into train and test sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

# Initialize models
models = {
    "SVM": SVC(),
    "Random Forest": RandomForestClassifier(),
    "AdaBoost": AdaBoostClassifier(),
    "Bagging": BaggingClassifier(),
    "Decision Tree": DecisionTreeClassifier()
}

# Train and evaluate models
for name, model in models.items():
    model.fit(x_train, y_train)
    y_pred = model.predict(x_test)

    accuracy = accuracy_score(y_test, y_pred)
    print(f"Accuracy for {name}: {accuracy:.2f}")

    conf_matrix = confusion_matrix(y_test, y_pred)
    print(f"Confusion Matrix for {name}:\n{conf_matrix}\n")


Accuracy for SVM: 0.94
Confusion Matrix for SVM:
[[10599  1062]
 [    0  5714]]

Accuracy for Random Forest: 0.95
Confusion Matrix for Random Forest:
[[10875   786]
 [   76  5638]]

Accuracy for AdaBoost: 0.92
Confusion Matrix for AdaBoost:
[[11094   567]
 [  779  4935]]

Accuracy for Bagging: 0.95
Confusion Matrix for Bagging:
[[10884   777]
 [   93  5621]]

Accuracy for Decision Tree: 0.95
Confusion Matrix for Decision Tree:
[[10882   779]
 [  107  5607]]



In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier, BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

# Assuming df is your original DataFrame
df = df.dropna()  # Drops rows containing any NaN values

# Now, you can proceed to split the data and train the model
x = df.iloc[:, :-1]
y = df.iloc[:, -1]

# Split data into train and test sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

# Initialize models
models = {
    # "SVM": SVC(),
    # "Random Forest": RandomForestClassifier(),
    # "Bagging": BaggingClassifier(),
    # "Decision Tree": DecisionTreeClassifier(),
    "KNN": KNeighborsClassifier()
}

# Train and evaluate models
for name, model in models.items():
    model.fit(x_train, y_train)
    y_pred = model.predict(x_test)

    accuracy = accuracy_score(y_test, y_pred)
    print(f"Accuracy for {name}: {accuracy:.2f}")

    conf_matrix = confusion_matrix(y_test, y_pred)
    print(f"Confusion Matrix for {name}:\n{conf_matrix}\n")


Accuracy for KNN: 0.94
Confusion Matrix for KNN:
[[10851   810]
 [  188  5526]]



In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier, BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Assuming df is your original DataFrame
df = df.dropna()  # Drops rows containing any NaN values

# Now, you can proceed to split the data and train the model
x = df.iloc[:, :-1]
y = df.iloc[:, -1]

# Split data into train and test sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

# Initialize models
models = {
    # "SVM": SVC(),
    # "Random Forest": RandomForestClassifier(),
    # "Bagging": BaggingClassifier(),
    # "Decision Tree": DecisionTreeClassifier(),
    "KNN": KNeighborsClassifier()
}

# Train and evaluate models
for name, model in models.items():
    model.fit(x_train, y_train)
    y_pred = model.predict(x_test)

    accuracy = accuracy_score(y_test, y_pred)
    print(f"Accuracy for {name}: {accuracy:.2f}")

    classification_rep = classification_report(y_test, y_pred)
    print(f"Classification Report for {name}:\n{classification_rep}")

    conf_matrix = confusion_matrix(y_test, y_pred)
    print(f"Confusion Matrix for {name}:\n{conf_matrix}\n")


Accuracy for KNN: 0.94
Classification Report for KNN:
              precision    recall  f1-score   support

           0       0.98      0.93      0.96     11661
           1       0.87      0.97      0.92      5714

    accuracy                           0.94     17375
   macro avg       0.93      0.95      0.94     17375
weighted avg       0.95      0.94      0.94     17375

Confusion Matrix for KNN:
[[10851   810]
 [  188  5526]]



In [ ]:
import plotly.graph_objs as go
from sklearn.metrics import roc_curve, auc
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
import pandas as pd
from sklearn.model_selection import train_test_split

# Assuming df is your original DataFrame
df = df.dropna()  # Drops rows containing any NaN values

# Now, you can proceed to split the data and train the model
x = df.iloc[:, :-1]
y = df.iloc[:, -1]

# Split data into train and test sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

# Train Random Forest model
rf_model = RandomForestClassifier()
rf_model.fit(x_train, y_train)

# Train XGBoost model
xgb_model = XGBClassifier()
xgb_model.fit(x_train, y_train)

# Calculate ROC curve and AUC for Random Forest
rf_probs = rf_model.predict_proba(x_test)[:, 1]
rf_fpr, rf_tpr, _ = roc_curve(y_test, rf_probs)
rf_auc = auc(rf_fpr, rf_tpr)

# Calculate ROC curve and AUC for XGBoost
xgb_probs = xgb_model.predict_proba(x_test)[:, 1]
xgb_fpr, xgb_tpr, _ = roc_curve(y_test, xgb_probs)
xgb_auc = auc(xgb_fpr, xgb_tpr)

# Plot ROC curve using Plotly
rf_trace = go.Scatter(x=rf_fpr, y=rf_tpr, mode='lines', name=f'Random Forest (AUC = {rf_auc:.2f})')
xgb_trace = go.Scatter(x=xgb_fpr, y=xgb_tpr, mode='lines', name=f'XGBoost (AUC = {xgb_auc:.2f})')

layout = go.Layout(
    title='ROC Curve',
    xaxis=dict(title='False Positive Rate'),
    yaxis=dict(title='True Positive Rate')
)

fig = go.Figure(data=[rf_trace, xgb_trace], layout=layout)
fig.show()


In [ ]:
import plotly.graph_objs as go
from sklearn.metrics import roc_curve, auc
from xgboost import XGBClassifier
import pandas as pd
from sklearn.model_selection import train_test_split

# Assuming df is your original DataFrame
df = df.dropna()  # Drops rows containing any NaN values

# Now, you can proceed to split the data and train the model
x = df.iloc[:, :-1]
y = df.iloc[:, -1]

# Split data into train and test sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

# Train XGBoost model
xgb_model = XGBClassifier()
xgb_model.fit(x_train, y_train)

# Calculate ROC curve and AUC for XGBoost
xgb_probs = xgb_model.predict_proba(x_test)[:, 1]
xgb_fpr, xgb_tpr, _ = roc_curve(y_test, xgb_probs)
xgb_auc = auc(xgb_fpr, xgb_tpr)

# Plot ROC curve using Plotly
xgb_trace = go.Scatter(x=xgb_fpr, y=xgb_tpr, mode='lines', name=f'XGBoost (AUC = {xgb_auc:.2f})')

layout = go.Layout(
    title='ROC Curve for XGBoost',
    xaxis=dict(title='False Positive Rate'),
    yaxis=dict(title='True Positive Rate'),
    height=500,  # Specify height
    width=800    # Specify width
)

fig = go.Figure(data=[xgb_trace], layout=layout)
fig.show()


In [ ]:
import plotly.graph_objs as go
from sklearn.metrics import roc_curve, auc
from xgboost import XGBClassifier
import pandas as pd
from sklearn.model_selection import train_test_split

# Assuming df is your original DataFrame
df = df.dropna()  # Drops rows containing any NaN values

# Now, you can proceed to split the data and train the model
x = df.iloc[:, :-1]
y = df.iloc[:, -1]

# Split data into train and test sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

# Train XGBoost model
xgb_model = XGBClassifier()
xgb_model.fit(x_train, y_train)

# Calculate ROC curve and AUC for XGBoost
xgb_probs = xgb_model.predict_proba(x_test)[:, 1]
fpr, tpr, _ = roc_curve(y_test, xgb_probs)
roc_auc = auc(fpr, tpr)

# Plot AUC curve using Plotly
auc_trace = go.Scatter(x=fpr, y=tpr, mode='lines', name=f'AUC Curve (AUC = {roc_auc:.2f})')

layout = go.Layout(
    title='AUC Curve for XGBoost',
    xaxis=dict(title='False Positive Rate'),
    yaxis=dict(title='True Positive Rate'),
    height=500,  # Specify height
    width=800    # Specify width
)

fig = go.Figure(data=[auc_trace], layout=layout)
fig.show()


In [ ]:
import plotly.figure_factory as ff

# Confusion Matrix for Random Forest Model
rf_conf_matrix = [[4467, 335],
                  [47, 1962]]

# Class labels
class_labels = ['Negative', 'Positive']

# Plotting Random Forest Confusion Matrix
rf_fig = ff.create_annotated_heatmap(z=rf_conf_matrix,
                                     x=class_labels,
                                     y=class_labels,
                                     colorscale='YlGnBu',
                                     showscale=True)  # Show color scale

# Add values inside cells for Random Forest Confusion Matrix
for i in range(len(class_labels)):
    for j in range(len(class_labels)):
        font_color = 'white' if rf_conf_matrix[i][j] == 4467 else 'black'  # Set font color to white for the value 4467
        rf_fig.add_annotation(text=str(rf_conf_matrix[i][j]),
                              x=class_labels[j], y=class_labels[i],
                              showarrow=False, font=dict(color=font_color))  # Set font color

# Update layout
rf_fig.update_layout(title_text="Confusion Matrix - Random Forest Model",
                     height=500, width=500)

rf_fig.show()


In [ ]:
import plotly.figure_factory as ff

# Confusion Matrix for XGBoost Model
xgb_conf_matrix = [[4463, 339],
                   [33, 1976]]

# Class labels
class_labels = ['Negative', 'Positive']

# Plotting XGBoost Confusion Matrix
xgb_fig = ff.create_annotated_heatmap(z=xgb_conf_matrix,
                                      x=class_labels,
                                      y=class_labels,
                                      colorscale='YlGnBu',
                                      showscale=True)  # Show color scale

# Add values inside cells for XGBoost Confusion Matrix
for i in range(len(class_labels)):
    for j in range(len(class_labels)):
        font_color = 'white' if xgb_conf_matrix[i][j] == 4463 else 'black'  # Set font color to white for the value 4463
        xgb_fig.add_annotation(text=str(xgb_conf_matrix[i][j]),
                               x=class_labels[j], y=class_labels[i],
                               showarrow=False, font=dict(color=font_color))  # Set font color

# Update layout
xgb_fig.update_layout(title_text="Confusion Matrix - XGBoost Model",
                      height=500, width=500)

xgb_fig.show()


In [ ]:
import plotly.figure_factory as ff
from plotly.subplots import make_subplots

# Confusion Matrix for Random Forest Model
rf_conf_matrix = [[4467, 335],
                  [47, 1962]]

# Confusion Matrix for XGBoost Model
xgb_conf_matrix = [[4463, 339],
                   [33, 1976]]

# Class labels
class_labels = ['Negative', 'Positive']

# Create subplots
fig = make_subplots(rows=1, cols=2, subplot_titles=("Random Forest Model", "XGBoost Model"))

# Plotting Random Forest Confusion Matrix
rf_fig = ff.create_annotated_heatmap(z=rf_conf_matrix,
                                     x=class_labels,
                                     y=class_labels,
                                     colorscale='YlGnBu',
                                     showscale=False)  # Hide color scale

# Plotting XGBoost Confusion Matrix
xgb_fig = ff.create_annotated_heatmap(z=xgb_conf_matrix,
                                      x=class_labels,
                                      y=class_labels,
                                      colorscale='YlGnBu',
                                      showscale=False)  # Hide color scale

# Add subplots
fig.add_trace(rf_fig.data[0], row=1, col=1)

# Add values inside cells for Random Forest Confusion Matrix
for i in range(len(class_labels)):
    for j in range(len(class_labels)):
        font_color = 'white' if rf_conf_matrix[i][j] == 4467 else 'black'  # Set font color to white for the value 4467
        fig.add_annotation(text=str(rf_conf_matrix[i][j]),
                              x=class_labels[j], y=class_labels[i],
                              showarrow=False, font=dict(color=font_color), row=1, col=1)  # Set font color

fig.add_trace(xgb_fig.data[0], row=1, col=2)

# Add values inside cells for XGBoost Confusion Matrix
for i in range(len(class_labels)):
    for j in range(len(class_labels)):
        font_color = 'white' if xgb_conf_matrix[i][j] == 4463 else 'black'  # Set font color to white for the value 4463
        fig.add_annotation(text=str(xgb_conf_matrix[i][j]),
                               x=class_labels[j], y=class_labels[i],
                               showarrow=False, font=dict(color=font_color), row=1, col=2)  # Set font color

# Update layout
fig.update_layout(title_text="Confusion Matrix Comparison", title_x=0.5,
                  height=500, width=1000,
                  margin=dict(l=0, r=5, t=50, b=50),  # Set margins (l=left, r=right, t=top, b=bottom)
                  plot_bgcolor='rgba(0,0,0,0)')  # Set plot background color to transparent

import plotly.io as pio

# Save the plot as PDF using plotly.io
pio.write_image(fig, 'confusion_matrix_comparison.pdf')



ValueError: 
Image export using the "kaleido" engine requires the kaleido package,
which can be installed using pip:
    $ pip install -U kaleido


In [ ]:
import plotly.graph_objs as go
from sklearn.metrics import roc_curve, auc
from xgboost import XGBClassifier
import pandas as pd
from sklearn.model_selection import train_test_split
import plotly.io as pio

# Assuming df is your original DataFrame
df = df.dropna()  # Drops rows containing any NaN values

# Now, you can proceed to split the data and train the model
x = df.iloc[:, :-1]
y = df.iloc[:, -1]

# Split data into train and test sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

# Train XGBoost model
xgb_model = XGBClassifier()
xgb_model.fit(x_train, y_train)

# Calculate ROC curve and AUC for XGBoost
xgb_probs = xgb_model.predict_proba(x_test)[:, 1]
fpr, tpr, _ = roc_curve(y_test, xgb_probs)
roc_auc = auc(fpr, tpr)

# Plot AUC curve using Plotly
auc_trace = go.Scatter(x=fpr, y=tpr, mode='lines', name=f'AUC Curve (AUC = {roc_auc:.2f})')

layout = go.Layout(
    title=dict(
        text='AUC Curve for XGBoost',
        x=0.5  # Center the title
    ),
    xaxis=dict(title='False Positive Rate'),
    yaxis=dict(title='True Positive Rate'),
    height=500,  # Specify height
    width=800    # Specify width
)

fig = go.Figure(data=[auc_trace], layout=layout)
fig.show()

# Save the plot as PDF using plotly.io
pio.write_image(fig, 'auc_curve_xgboost.pdf')


In [ ]:
df


In [ ]:
# import plotly.figure_factory as ff

# # Subset the DataFrame based on selected features
# X_subset = X[selected_features]

# # Calculate correlation matrix
# corr_matrix = X_subset.corr().round(1)  # Round to 1 decimal place

# # Define feature labels
# feature_labels = {
#     'Age': 'Age',
#     'Bachelor': 'Bach.',
#     'B_SUBJECT': 'B_Subj.',
#     'Bachelor Education Organization (Public / Private)': 'Bach. Edu Org',
#     'Technical Skill': 'Tech. Skill',
#     'SOFT Skill': 'Soft Skill',
#     'Masters': 'Masters',
#     'm_SUBJECT': 'm_Subj.',
#     'Masters Education Organization (Public / Private)': 'Masters Edu Org'
# }

# # Create a heatmap using Plotly with customized labels
# fig = ff.create_annotated_heatmap(z=corr_matrix.values,
#                                   x=[feature_labels[col] for col in corr_matrix.columns],
#                                   y=[feature_labels[row] for row in corr_matrix.index],
#                                   colorscale='Viridis')

# # Update layout with height and width settings
# fig.update_layout(title_text='Correlation Heatmap of Selected Features',
#                   title_x=0.5,  # Set title position in the middle
#                   margin=dict(l=0, r=5, t=120, b=5),  # Remove extra margins
#                   height=600,  # Set the height
#                   width=800)  # Set the width

# # Show the plot
# pio.write_image(fig, 'hitmap.pdf')


In [ ]:
import plotly.graph_objects as go
import plotly.io as pio


# Assuming df is your DataFrame containing the 'output' column
# Count the occurrences of each output value
output_counts = df['output'].value_counts()

# Create a bar chart using Plotly
fig = go.Figure(data=[go.Bar(
    x=output_counts.index,  # Output values
    y=output_counts.values,  # Count of each output value
    text=output_counts.values,  # Text labels for each bar
    textposition='auto',  # Position of the text labels
    marker_color=['orange', 'blue']  # Colors for bars (orange for 1, blue for 0)
)])

# Update layout
fig.update_layout(title_text='Distribution of Output Values',
                  title_x=0.5,  # Set title position in the middle
                  xaxis_title='Output', yaxis_title='Count',
                  height=400, width=600,  # Set height and width
                  plot_bgcolor='white',  # Set plot background color to white
                  paper_bgcolor='white',  # Set paper background color to white
                  xaxis=dict(tickvals=[0, 1], ticktext=['Not Offer (0)', 'Offer (1)']))  # Set tick labels for x-axis

# Show the plot
pio.write_image(fig, 'output.pdf')


In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix
from tensorflow import keras
from tensorflow.keras import layers

# Assuming df is your DataFrame with the provided columns

# Split features and target variable
X = df.drop(columns=['output'])
y = df['output']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Preprocessing: Standardize numerical variables
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Define the neural network architecture
model = keras.Sequential([
    layers.Dense(64, activation='relu', input_shape=(X_train_scaled.shape[1],)),
    layers.Dense(32, activation='relu'),
    layers.Dense(1, activation='sigmoid')
])

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
history = model.fit(X_train_scaled, y_train, epochs=10, batch_size=32, validation_data=(X_test_scaled, y_test))

# Evaluate the model
y_pred = model.predict_classes(X_test_scaled)

# Generate confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(conf_matrix)

# Generate classification report
class_report = classification_report(y_test, y_pred)
print("Classification Report:")
print(class_report)


In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix
from tensorflow import keras
from tensorflow.keras import layers

# Assuming df is your DataFrame with the provided columns

# Split features and target variable
X = df.drop(columns=['output'])
y = df['output']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Preprocessing: Standardize numerical variables
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Define the neural network architecture
model = keras.Sequential([
    layers.Dense(64, activation='relu', input_shape=(X_train_scaled.shape[1],)),
    layers.Dense(32, activation='relu'),
    layers.Dense(1, activation='sigmoid')
])

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
history = model.fit(X_train_scaled, y_train, epochs=10, batch_size=32, validation_data=(X_test_scaled, y_test))

# Predict probabilities
y_pred_prob = model.predict(X_test_scaled)
# Convert probabilities to classes using a threshold (e.g., 0.5)
y_pred = (y_pred_prob > 0.5).astype(int)

# Generate confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix ANN:")
print(conf_matrix)

# Generate classification report
class_report = classification_report(y_test, y_pred)
print("Classification Report:")
print(class_report)


In [ ]:
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix

# Assuming df is your DataFrame with the provided columns

# Split features and target variable
X = df.drop(columns=['output'])
y = df['output']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Preprocessing: Standardize numerical variables
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Define the MLP model
model = MLPClassifier(hidden_layer_sizes=(64, 32), activation='relu', solver='adam', random_state=42)

# Train the model
model.fit(X_train_scaled, y_train)

# Predict classes
y_pred = model.predict(X_test_scaled)

# Generate confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix MLP:")
print(conf_matrix)

# Generate classification report
class_report = classification_report(y_test, y_pred)
print("Classification Report:")
print(class_report)


In [ ]:
from sklearn.ensemble import AdaBoostClassifier

# Define the AdaBoost classifier
ada_model = AdaBoostClassifier()

# Train the model
ada_model.fit(X_train_scaled, y_train)

# Predict probabilities
y_pred_prob_ada = ada_model.predict_proba(X_test_scaled)[:, 1]

# Convert probabilities to classes using a threshold (e.g., 0.5)
y_pred_ada = (y_pred_prob_ada > 0.5).astype(int)

# Generate confusion matrix
conf_matrix_ada = confusion_matrix(y_test, y_pred_ada)
print("Confusion Matrix AdaBoost:")
print(conf_matrix_ada)

# Generate classification report
class_report_ada = classification_report(y_test, y_pred_ada)
print("Classification Report AdaBoost:")
print(class_report_ada)
from sklearn.metrics import accuracy_score

# Calculate accuracy
accuracy_ada = accuracy_score(y_test, y_pred_ada)
print("Accuracy AdaBoost:", accuracy_ada)


In [ ]:
from sklearn.linear_model import LogisticRegression

# Define the Logistic Regression model
lr_model = LogisticRegression()

# Train the model
lr_model.fit(X_train_scaled, y_train)

# Predict probabilities
y_pred_prob_lr = lr_model.predict_proba(X_test_scaled)[:, 1]

# Convert probabilities to classes using a threshold (e.g., 0.5)
y_pred_lr = (y_pred_prob_lr > 0.5).astype(int)

# Generate confusion matrix
conf_matrix_lr = confusion_matrix(y_test, y_pred_lr)
print("Confusion Matrix Logistic Regression:")
print(conf_matrix_lr)

# Generate classification report
class_report_lr = classification_report(y_test, y_pred_lr)
print("Classification Report Logistic Regression:")
print(class_report_lr)
# Calculate accuracy
accuracy_lr = accuracy_score(y_test, y_pred_lr)
print("Accuracy Logistic Regression:", accuracy_lr)


In [ ]:
from sklearn.ensemble import GradientBoostingClassifier

# Define the GBM model
gbm_model = GradientBoostingClassifier()

# Train the model
gbm_model.fit(X_train_scaled, y_train)

# Predict probabilities
y_pred_prob_gbm = gbm_model.predict_proba(X_test_scaled)[:, 1]

# Convert probabilities to classes using a threshold (e.g., 0.5)
y_pred_gbm = (y_pred_prob_gbm > 0.5).astype(int)

# Generate confusion matrix
conf_matrix_gbm = confusion_matrix(y_test, y_pred_gbm)
print("Confusion Matrix GBM:")
print(conf_matrix_gbm)

# Generate classification report
class_report_gbm = classification_report(y_test, y_pred_gbm)
print("Classification Report GBM:")
print(class_report_gbm)
# Calculate accuracy
accuracy_gbm = accuracy_score(y_test, y_pred_gbm)
print("Accuracy GBM:", accuracy_gbm)


In [ ]:
from sklearn.naive_bayes import GaussianNB

# Define the Naive Bayes model
nb_model = GaussianNB()

# Train the model
nb_model.fit(X_train_scaled, y_train)

# Predict probabilities
y_pred_prob_nb = nb_model.predict_proba(X_test_scaled)[:, 1]

# Convert probabilities to classes using a threshold (e.g., 0.5)
y_pred_nb = (y_pred_prob_nb > 0.5).astype(int)

# Generate confusion matrix
conf_matrix_nb = confusion_matrix(y_test, y_pred_nb)
print("Confusion Matrix Naive Bayes:")
print(conf_matrix_nb)

# Generate classification report
class_report_nb = classification_report(y_test, y_pred_nb)
print("Classification Report Naive Bayes:")
print(class_report_nb)
# Calculate accuracy
accuracy_nb = accuracy_score(y_test, y_pred_nb)
print("Accuracy Naive Bayes:", accuracy_nb)


In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from tensorflow import keras
from tensorflow.keras import layers

# Assuming df is your DataFrame with the provided columns

# Split features and target variable
X = df.drop(columns=['output'])
y = df['output']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Preprocessing: Standardize numerical variables
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Define the neural network architecture
model = keras.Sequential([
    layers.Dense(64, activation='relu', input_shape=(X_train_scaled.shape[1],)),
    layers.Dense(32, activation='relu'),
    layers.Dense(1, activation='sigmoid')
])

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
history = model.fit(X_train_scaled, y_train, epochs=10, batch_size=32, validation_data=(X_test_scaled, y_test))

# Predict probabilities
y_pred_prob = model.predict(X_test_scaled)

# Predict classes
y_pred_classes = (y_pred_prob > 0.5).astype(int)

# Generate confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred_classes)
print("Confusion Matrix ANN:")
print(conf_matrix)

# Generate classification report
class_report = classification_report(y_test, y_pred_classes)
print("Classification Report:")
print(class_report)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred_classes)
print("Accuracy:", accuracy)
